items/urls.py
from django.conf.urls import url
from items import views


urlpatterns = [
    url(r'^$', views.items, name='items'),
    url(r'^my$', views.user_items, name='items.my'),
    url(r'^creation$', views.creation_page, name='items.creation'),
    url(r'^creation/save$', views.create, name='items.creation.save'),

    url(r'^(?P<id>\d+)/editing$', views.editing_page, name='items.editing'),
    url(r'^(?P<id>\d+)/save$', views.edit, name='items.editing.save'),

    url(r'^(?P<id>\d+)/delete$', views.delete, name='items.delete'),
    url(r'^photo_upload$', views.photo_upload, name='item_photo_upload'),
    url(r'^logo_upload$', views.logo_upload, name='item_logo_upload'),
    url(r'^(?P<id>\d+)/complaint', views.send_complaint, name='item_send_complaint'),
    url(r'^(?P<id>\d+)/phone_image', views.get_phone_image, name='item_phone_image'),
    url(r'^(?P<id>\d+)/feedback', views.send_feedback, name='items.feedback.creation.save'),
]

news/urls.py
from django.conf.urls import url
from news import views

urlpatterns = [
    url(r'^$', views.news, name='news.index'),
    url(r'^(?P<id>\d+)$', views.article, name='news.article'),
]

items/models/base.py
# Объявление, общие данные
from django.db import models
from model_utils import Choices
from utils.models import Image


class Base(models.Model):
    type = models.ForeignKey('items.Type', on_delete=models.SET_NULL, null=True)  # Тип объявления
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.PositiveIntegerField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=19, decimal_places=15, null=True, blank=True)
    longitude = models.DecimalField(max_digits=19, decimal_places=15, null=True, blank=True)
    region = models.ForeignKey('utils.Region', on_delete=models.SET_NULL, null=True)  # Регион
    views = models.IntegerField(default=0, blank=True, null=True)
    user = models.ForeignKey('extusers.ExtUser', on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    published_at = models.DateTimeField(auto_now_add=True, null=True)
    photos = models.ManyToManyField(Image, related_name='photos')
    complaints = models.ManyToManyField('items.Complaint', blank=True)
    logo = models.ForeignKey('utils.Image', on_delete=models.SET_NULL, null=True)
    is_fake = models.BooleanField(default=False, blank=True)
    STATUSES = Choices(
        (0, 'deleted', 'Удалено'),
        (1, 'active', 'Активно'))
    status = models.IntegerField(choices=STATUSES, default=STATUSES.active)

    @property
    def is_sale(self):
        if self.type.code_name == 'sale':
            return True
        return False

    @property
    def is_lost(self):
        if self.type.code_name == 'lost':
            return True
        return False

    @property
    def is_find(self):
        if self.type.code_name == 'find':
            return True
        return False

    @property
    def is_gift(self):
        if self.type.code_name == 'gift':
            return True
        return False

    def __str__(self):
        return str(self.id)+' '+str(self.title)

items/models/category.py
# Категория объявления
from django.db import models
from model_utils import Choices


class Category(models.Model):
    name = models.CharField(max_length=100)
    url_alias = models.CharField(max_length=150, null=True)
    alias = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    STATUSES = Choices(
        (0, 'deleted', 'Удалено'),
        (1, 'active', 'Активно'))
    status = models.IntegerField(choices=STATUSES, default=STATUSES.active)

    def __str__(self):
        return self.name

items/models/feedback.py
from django.db import models
from model_utils import Choices


class Feedback(models.Model):
    email = models.EmailField('Электронная почта', max_length=255)
    name = models.CharField(max_length=300, blank=True)
    text = models.TextField(max_length=500)
    user = models.ForeignKey('extusers.ExtUser', on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    STATUSES = Choices(
        (0, 'deleted', 'Удалено'),
        (1, 'active', 'Активно'))
    status = models.IntegerField(choices=STATUSES, default=STATUSES.active)

    def __str__(self):
        return self.name

items/models/pet.py
# Объявления о животных
from django.db import models
from django.urls import reverse
from model_utils import Choices
from items.models.base import Base


class Pet(Base):
    breed = models.ForeignKey('animals.Breed', null=True, blank=True)  # Порода
    kind = models.ForeignKey('animals.Kind', null=True)
    nickname = models.CharField(max_length=100, null=True, blank=True)  # Кличка
    GENDER = Choices(
        (0, 'female', 'Самка'),
        (1, 'male', 'Самец'))
    gender = models.IntegerField(choices=GENDER, default=GENDER.male)

    def get_absolute_url(self):
        return reverse('item', args=[
            self.region.url_alias,
            self.type.url_alias,
            self.kind.url_alias,
            self.pk
        ])

animals/forms/breed.py
__author__ = 'dimuska139'

from django.forms import ModelForm
from animals.models import Breed


class BreedForm(ModelForm):
    class Meta:
        model = Breed
        exclude = (
            'logo_url',
            'status'
        )

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Название породы'
        self.fields['kind'].label = 'Вид животного'
        self.fields['logo'].label = 'Логотип'

items/forms.py
# -*- coding: utf-8 -*-
from extusers.models import ExtUser
from items.models import Type

__author__ = 'dimuska139'


from django import forms
from django.conf import settings
from .models import Base, Pet, Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ('status', )


class BaseForm(forms.ModelForm):
    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=17)

    class Meta:
        model = Base
        exclude = ()

    def clean_photos(self):
        photos_list = self.cleaned_data.get('photos')
        if photos_list.count() > settings.MAX_ITEM_PHOTOS_AMOUNT:
            raise forms.ValidationError('Загружено более ' + str(settings.MAX_ITEM_PHOTOS_AMOUNT) + ' фотографий')
        return photos_list

    def clean_price(self):
        if self.cleaned_data.get('type') == Type.selling() and self.cleaned_data.get('price') is None:
            raise forms.ValidationError('Не указана цена')
        return self.cleaned_data.get('price')


class PetForm(BaseForm):
    class Meta:
        model = Pet
        exclude = (
            'views',
            'published_at',
            'status',
            'user',
            'complaints',
            'url'
        )

    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        self.fields['kind'].label = 'Животное'
        self.fields['breed'].label = 'Порода'
        self.fields['nickname'].label = 'Кличка'
        self.fields['gender'].label = 'Пол'
        self.fields['logo'].label = 'Миниатюра'
        self.fields['photos'].label = 'Фотографии'
        self.fields['type'].label = 'Тип объявления'
        self.fields['price'].label = 'Цена'
        self.fields['title'].label = 'Заголовок'
        self.fields['description'].label = 'Описание'
        self.fields['address'].label = 'Место (адрес)'
        self.fields['latitude'].label = 'Широта'
        self.fields['longitude'].label = 'Долгота'
        self.fields['region'].label = 'Регион'

items/views.py
# --*-- coding: utf-8 --*--
import base64
import hashlib
from django import template
from django.contrib import messages

from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.http.response import JsonResponse, Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.template.loader import render_to_string
from django.urls import reverse

from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.conf import settings
from django.core.cache import cache
from django.db.models import Q
from honeypot.decorators import check_honeypot
from jsonview.decorators import json_view

from extusers.decorators import login_required_json
from items.forms import FeedbackForm
from animals.models import Characteristic
from animals.models import PetCharacteristic
from animals.models import Breed
from animals.models import Kind
from utils.forms import get_errors
from .forms import PetForm
from extusers.models import ExtUser
from .models import Base, Pet, Type, Category, Complaint, ComplaintType
from utils.models import Region
from utils.models import Image
from PIL import ImageDraw, ImageFont
from PIL import Image as PILImage


import json
import os
import io


@json_view
def send_complaint(request, id):
    if 'complaint_type' not in request.POST:
        raise Http404
    if not ComplaintType.objects.filter(status=ComplaintType.STATUSES.active,
                                        code_name=request.POST['complaint_type']).exists():
        raise Http404
    item = get_object_or_404(Base, pk=id, status=Base.STATUSES.active)
    type = get_object_or_404(ComplaintType, code_name=request.POST['complaint_type'])
    complaint = Complaint()
    complaint.type = type
    if 'comment' in request.POST and len(request.POST['comment']) > 0:
        complaint.comment = request.POST['comment']
    if not request.user.is_anonymous():
        complaint.user = request.user
    complaint.save()
    item.complaints.add(complaint)
    return {
        'success': True,
        'error': ''
    }


def get_breeds():
    breeds = list(Breed.objects.filter(status=Breed.STATUSES.active).order_by('name'))
    dog_breeds = []
    cat_breeds = []
    bird_breeds = []
    for breed in breeds:
        if breed.kind_id == 1:
            dog_breeds.append({'id': str(breed.id), 'name': breed.name})
        if breed.kind_id == 2:
            cat_breeds.append({'id': str(breed.id), 'name': breed.name})
        if breed.kind_id == 3:
            bird_breeds.append({'id': str(breed.id), 'name': breed.name})
    return dog_breeds, cat_breeds, bird_breeds


# @cache_page(60 * 15)
def item(request, region_alias, type_alias, kind_alias, id):
    # Проверка url
    exists_region = Region.objects.filter(status=Region.STATUSES.active, url_alias=region_alias).exists()
    if not exists_region:
        raise Http404

    exists_type = Type.objects.filter(status=Type.STATUSES.active, url_alias=type_alias).exists()
    if not exists_type:
        raise Http404

    exists_kind = Kind.objects.filter(status=Kind.STATUSES.active, url_alias=kind_alias).exists()
    if not exists_kind:
        raise Http404

    if not Pet.objects.filter(id=id).exists():
        raise Http404

    pet = Pet.objects.get(id=id)
    if 'viewed_items' in request.COOKIES:
        viewed_items = json.loads(request.COOKIES.get('viewed_items'))
    else:
        viewed_items = []

    if request.user.is_authenticated and request.user.id == pet.user_id:
        is_owner = True
    else:
        is_owner = False
        if pet.status != Pet.STATUSES.active:
            raise Http404

        if not pet.id in viewed_items:
            pet.views += 1
            pet.save()
            viewed_items.append(pet.id)

    complaint_types = ComplaintType.objects.filter(status=ComplaintType.STATUSES.active,
                                                   category_id=pet.type.category_id)

    template = loader.get_template('items/pages/item.html')
    if request.user.is_authenticated:
        feedback_form = FeedbackForm(initial={
            'name': request.user.name,
            'email': request.user.email
        })
    else:
        feedback_form = FeedbackForm(initial={
            'name': '',
            'email': ''
        })
    context = {
        'item': pet,
        'complaint_types': complaint_types,
        'is_owner': is_owner,
        'id': pet.pk,
        'feedback_form': feedback_form,
        'page_id': 'item_' + str(pet.pk),
    }

    response = HttpResponse(template.render(context, request))
    response.set_cookie('viewed_items', json.dumps(viewed_items))
    return response


# Создание изображения номера телефона
@json_view
def get_phone_image(request, id):
    if not Base.objects.filter(id=id, status=Base.STATUSES.active).exists():
        return {
            'success': False,
            'message': 'Item not found',
            'html': ''
        }

    phone = Base.objects.get(id=id, status=Base.STATUSES.active).user.phone

    font_size = 30
    image = PILImage.new('RGBA', (250, 40), (255, 255, 255, 0))
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(os.path.dirname(__file__) + '/phone_font/UbuntuBold.ttf', font_size)
    draw.text((0, 2), phone, font=font, fill='#3c763d')
    output = io.BytesIO()
    image.save(output, format="PNG")
    contents = base64.b64encode(output.getvalue()).decode()
    output.close()

    template = loader.get_template('items/phone_image.html')
    context = {
        'image_base64': contents
    }
    return {
        'success': True,
        'message': '',
        'html': template.render(context, request)
    }


@json_view
@login_required_json
def delete(request, id):
    item = Pet.objects.get(pk=id)
    if item.user_id != request.user.id:
        return {
            'success': False
        }
    item.status = Pet.STATUSES.deleted
    item.save()
    response = {
        'success': True,
    }
    return response


@login_required
def editing_page(request, id):
    if request.user.is_superuser:  # Админ может редактировать любые объявления
        item = get_object_or_404(Pet, id=id)
    else:  # Остальные пользователи - только свои
        item = get_object_or_404(Pet, id=id, user_id=request.user.id)
    dog_breeds, cat_breeds, bird_breeds = get_breeds()
    regions = Region.objects.filter(status=Region.STATUSES.active).order_by('-items_amount', 'name')
    types = Type.objects.filter(status=Type.STATUSES.active)
    kinds = Kind.objects.filter(status=Kind.STATUSES.active)

    max_photos_amount = getattr(settings, 'MAX_ITEM_PHOTOS_AMOUNT', 3)

    pet_form = PetForm(instance=item)
    template = loader.get_template('items/pages/pet_editing.html')

    photos = item.photos.all()
    logo = item.logo

    context = {
        'kinds': kinds,
        'types': types,
        'cat_breeds': cat_breeds,
        'dog_breeds': dog_breeds,
        'bird_breeds': bird_breeds,
        'regions': regions,
        'pet_form': pet_form,
        'max_photos_amount': max_photos_amount,
        'user': request.user,
        'photos': photos,
        'logo': logo,
        'item_id': id
    }
    return HttpResponse(template.render(context, request))


@json_view
@login_required_json
def edit(request, id):
    if request.user.is_superuser:  # Админ может редактировать любые объявления
        item = Pet.objects.filter(id=id, status=Pet.STATUSES.active).first()
    else:  # Остальные пользователи - только свои
        item = Pet.objects.filter(id=id, user_id=request.user.id, status=Pet.STATUSES.active).first()

    if not item:
        return {
            'success': False,
            'errors': [
                {
                    'key': 'all',
                    'description': 'Объявление не найдено'
                }
            ]
        }

    pet_form = PetForm(request.POST, instance=item)
    if not pet_form.is_valid():
        return {
            'success': False,
            'errors': get_errors(pet_form)
        }

    pet = pet_form.save(commit=False)
    pet.user = ExtUser.objects.get(pk=request.user.id)

    pet.published_at = pet.created_at
    pet.status = Pet.STATUSES.active
    pet.save()

    # Обновление имени и телефона пользователя
    request.user.name = pet_form.cleaned_data['name']
    request.user.phone = pet_form.cleaned_data['phone']
    request.user.save()

    pet.logo.make_logo(x1=request.POST['logo_x1'],
                       y1=request.POST['logo_y1'],
                       x2=request.POST['logo_x2'],
                       y2=request.POST['logo_y2'])

    item.photos.through.objects.all().delete()

    # Связать загруженные фотографии с созданным объявлением
    photos_ids = request.POST.getlist('photos')
    photos = Image.objects.filter(id__in=photos_ids).all()
    for photo in photos:
        pet.photos.add(photo)

    # Увеличить счётчик количества объявлений для соответствующего региона
    region = Region.objects.filter(id=pet.region_id).first()
    region.items_amount += 1
    region.save()

    template = loader.get_template('items/messages/item_editing_success.html')

    context = {
        'item': item,
    }
    messages.info(request, template.render(context, request))
    return {
        'success': True,
        'url': reverse('items.my')
    }


@login_required
def creation_page(request):
    dog_breeds, cat_breeds, bird_breeds = get_breeds()
    regions_list = Region.objects.filter(status=Region.STATUSES.active).order_by('-items_amount', 'name')
    regions = []
    for region in regions_list:
        regions.append({

templates/items/forms/item_pet_master.html
{% load floattags %}
{% load static %}

{% csrf_token %}
<input type="hidden" name="logo" id="logo_id" value="{{ logo.pk }}">
<input type="hidden" name="logo_x1" id="logo_x1" value="{{ logo.x_1 }}">
<input type="hidden" name="logo_x2" id="logo_x2" value="{{ logo.x_2 }}">
<input type="hidden" name="logo_y1" id="logo_y1" value="{{ logo.y_1 }}">
<input type="hidden" name="logo_y2" id="logo_y2" value="{{ logo.y_2 }}">
<input type="hidden" name="latitude" id="latitude" value="{{ form.latitude.value }}">
<input type="hidden" name="longitude" id="longitude" value="{{ form.longitude.value }}">


    <div class="card-block">
        <div class="form-group row{% if form.type.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.type.label }}</label>
            <div class="col-md-9">
                <div class="btn-group" data-toggle="buttons" id="id_type">
                    {% for type in types %}
                        {% if type.id == form.type.value %}
                        <label class="btn active" aria-pressed="true">
                            <input class="type" type="radio" value="{{ type.id }}" name="type" checked> {{ type.name }}
                        </label>
                        {% else %}
                        <label class="btn">
                            <input class="type" type="radio" value="{{ type.id }}" name="type"> {{ type.name }}
                        </label>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="form-control-feedback">{{ form.type.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.kind.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.kind.label }}</label>
            <div class="col-md-9">
                <div class="btn-group" data-toggle="buttons" id="id_kind">
                    {% for kind in kinds %}
                        {% if kind.id == form.kind.value %}
                        <label class="btn active" aria-pressed="true">
                            <input class="kind" type="radio" value="{{ kind.id }}" name="kind" autocomplete="off" checked> {{ kind.name }}
                        </label>
                        {% else %}
                        <label class="btn">
                            <input class="kind" type="radio" value="{{ kind.id }}" name="kind"> {{ kind.name }}
                        </label>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="form-control-feedback">{{ form.kind.errors }}</div>
            </div>
        </div>
        <div class="breed-place form-group row{% if form.breed.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.breed.label }}</label>
            <div class="col-md-9">
                <select id="breed-selector" class="form-control"></select>
                <input type="hidden" name="breed" value="{{ form.breed.value }}" id="id_breed">
                <div class="form-control-feedback">{{ form.breed.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.gender.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.gender.label }}</label>
            <div class="col-md-9">
                <div class="btn-group" data-toggle="buttons" id="id_gender">
                    {% if form.gender.value == '0' or form.gender.value == 0 %}
                        <label class="btn active" aria-pressed="true">
                            <input type="radio" value="0" name="gender" autocomplete="off" checked> Самка
                        </label>
                    {% else %}
                        <label class="btn" aria-pressed="false">
                            <input type="radio" value="0" name="gender" autocomplete="off"> Самка
                        </label>
                    {% endif %}
                    {% if form.gender.value == '1' or form.gender.value == 1 %}
                        <label class="btn active" aria-pressed="true">
                            <input type="radio" value="1" name="gender" autocomplete="off" checked> Самец
                        </label>
                    {% else %}
                        <label class="btn" aria-pressed="false">
                            <input type="radio" value="1" name="gender" autocomplete="off"> Самец
                        </label>
                    {% endif %}
                </div>
                <div class="form-control-feedback">{{ form.gender.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.nickname.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.nickname.label }}</label>
            <div class="col-md-9">
                {% if form.nikname.value %}
                <input id="id_nickname" type="text" class="form-control" name="{{ form.nickname.name }}" placeholder="{{ form.nickname.label }}" value="{{ form.nickname.value }}">
                {% else %}
                <input id="id_nickname" type="text" class="form-control" name="{{ form.nickname.name }}" placeholder="{{ form.nickname.label }}">
                {% endif %}
                <div class="form-control-feedback">{{ form.nickname.errors }}</div>
            </div>
        </div>
        <div class="price-line form-group row{% if form.price.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.price.label }}</label>
            <div class="col-md-9">
                {% if form.price.value %}
                <input id="id_price" type="text" class="form-control" name="{{ form.price.name }}" placeholder="{{ form.price.label }}" value="{{ form.price.value }}">
                {% else %}
                <input id="id_price" type="text" class="form-control" name="{{ form.price.name }}" placeholder="{{ form.price.label }}">
                {% endif %}
                <div class="form-control-feedback">{{ form.price.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.title.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.title.label }}</label>
            <div class="col-md-9">
                <input id="id_title" type="text" class="form-control" name="{{ form.title.name }}" placeholder="{{ form.title.label }}" value="{{ form.title.value }}">
                <div class="form-control-feedback">{{ form.title.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.description.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.description.label }}</label>
            <div class="col-md-9">
                <textarea id="id_description" class="form-control" name="{{ form.description.name }}" placeholder="{{ form.description.label }}">{{ form.description.value }}</textarea>
                <small class="form-text text-muted">В описании запрещено указывать ссылки</small>
                <div class="form-control-feedback">{{ form.description.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.logo.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.logo.label }}</label>
            <div class="col-md-9">
                <div class="crop-widget">
                    <div class="form-control btn btn-success btn-upload">
                        <input id="id_logo" type="file" name="image" class="logo-upload" data-url="{% url 'item_logo_upload' %}">
                        Прикрепить фотографию <span class="fa fa-cloud-upload"></span>
                    </div>
                    <progress class="progress progress-success w-100" value="0" max="100"></progress>
                    <small class="form-text text-muted">Фотография будет отображаться в списке объявлений</small>
                    <div class="alert alert-danger error" role="alert"></div>
                    <div class="image-place">
                        {% if logo.original %}
                        <img class="image" src="{{ logo.original.url }}"/>
                        {% endif %}
                    </div>
                    <div class="form-control-feedback">{{ form.logo.errors }}</div>
                </div>

            </div>
        </div>
        <div class="form-group row{% if form.photos.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.photos.label }}</label>
            <div class="col-md-9">
                <div class="image-widget">
                    <div class="form-control btn btn-success btn-upload">
                        <input id="id_photos" type="file" name="photo" class="photo-upload" data-url="{% url 'item_photo_upload' %}">
                        Прикрепить фотографию <span class="fa fa-cloud-upload"></span>
                    </div>
                    <progress class="progress progress-success w-100" value="0" max="100"></progress>
                    <small class="form-text text-muted">Максимум - {{ max_photos_amount }} изображения</small>
                    <div class="alert alert-danger error" role="alert"></div>
                    <div class="photos">
                        <div class="photos-container">
                            {% for photo in photos %}
                                {% include "items/uploaded_photo.html" %}
                            {% endfor %}
                        </div>
                        <div class="form-control-feedback">{{ form.photos.errors }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row{% if form.region.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.region.label }}</label>
            <div class="col-md-9">
                <select id="region-selector" class="form-control">
                    <option value="">Не выбран</option>
                    {% for region in regions %}
                        <option value="{{ region.id }}" data-latitude="{{ region.latitude|formatted_float }}" data-longitude="{{ region.longitude|formatted_float }}">{{ region.name }}</option>
                    {% endfor %}
                </select>
                <input type="hidden" name="region" value="{{ form.region.value }}" id="id_region">
                <div class="form-control-feedback">{{ form.region.errors }}</div>
            </div>
        </div>
        <div class="form-group row{% if form.address.errors %} has-danger{% endif %}">
            <label class="col-md-3 col-form-label">{{ form.address.label }}</label>
            <div class="col-md-9">
                <input type="text" class="form-control" name="address" id="id_address" placeholder="Введите точный адрес" value="{{ form.address.value }}"/>
                <div class="map"></div>
                <div class="form-control-feedback">{{ form.address.errors }}</div>
            </div>
        </div>
        {% if form.name.value %}
            <div class="form-group row{% if form.name.errors %} has-danger{% endif %}">
                <label class="col-md-3 col-form-label">Ваше имя</label>
                <div class="col-md-9">
                    <input readonly id="id_name" name="name" type="text" class="form-control" value="{{ form.name.value }}">
                    <small class="form-text text-muted">Можно изменить в настройках профиля</small>
                    <div class="form-control-feedback">{{ form.name.errors }}</div>
                </div>
            </div>
        {% else %}
            <div class="form-group row{% if form.name.errors %} has-danger{% endif %}">
                <label class="col-md-3 col-form-label">Ваше имя</label>
                <div class="col-md-9">
                    <input id="id_name" name="name" type="text" class="form-control" value="{{ form.name.value }}">
                    <div class="form-control-feedback">{{ form.name.errors }}</div>
                </div>
            </div>
        {% endif %}
        {% if form.phone.value %}
            <div class="form-group row{% if form.phone.errors %} has-danger{% endif %}">
                <label class="col-md-3 col-form-label">Телефон</label>
                <div class="col-md-9">
                    <input readonly id="id_phone" name="phone" type="text" class="form-control" value="{{ form.phone.value }}">
                    <small class="form-text text-muted">Можно изменить в настройках профиля</small>
                    <div class="form-control-feedback">{{ form.phone.errors }}</div>
                </div>
            </div>
        {% else %}
            <div class="form-group row{% if form.phone.errors %} has-danger{% endif %}">
                <label class="col-md-3 col-form-label">Телефон</label>
                <div class="col-md-9">
                    <input id="id_phone" name="phone" type="text" class="form-control" value="{{ form.phone.value }}">
                    <div class="form-control-feedback">{{ form.phone.errors }}</div>
                </div>
            </div>
        {% endif %}
        <div class="form-group row">
            <label class="col-md-3 col-form-label">Email</label>
            <div class="col-md-9">
                <input disabled type="text" class="form-control" value="{{ user.email }}">
                <small class="form-text text-muted">Можно изменить в настройках профиля</small>
            </div>
        </div>
        <div class="alert alert-danger non-field-errors" role="alert">
            {{ form.non_field_errors }}
        </div>
    </div>