feedback/urls.py
from django.conf.urls import url
from feedback import views

urlpatterns = [
    url(r'^create$', views.create, name='feedback.create')
]

news/urls.py
from django.conf.urls import url
from news import views

urlpatterns = [
    url(r'^$', views.news, name='news.index'),
    url(r'^(?P<id>\d+)$', views.article, name='news.article'),
]

feedback/models/feedback.py
from django.db import models
from model_utils import Choices


class Feedback(models.Model):
    text = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()

    STATUSES = Choices(
        (0, 'deleted', 'Удалено'),
        (1, 'active', 'Активно'))
    status = models.IntegerField(choices=STATUSES, default=STATUSES.active)

    def __str__(self):
        return self.name

items/models/feedback.py
from django.db import models
from model_utils import Choices


class Feedback(models.Model):
    email = models.EmailField('Электронная почта', max_length=255)
    name = models.CharField(max_length=300, blank=True)
    text = models.TextField(max_length=500)
    user = models.ForeignKey('extusers.ExtUser', on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    STATUSES = Choices(
        (0, 'deleted', 'Удалено'),
        (1, 'active', 'Активно'))
    status = models.IntegerField(choices=STATUSES, default=STATUSES.active)

    def __str__(self):
        return self.name

animals/forms/breed.py
__author__ = 'dimuska139'

from django.forms import ModelForm
from animals.models import Breed


class BreedForm(ModelForm):
    class Meta:
        model = Breed
        exclude = (
            'logo_url',
            'status'
        )

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Название породы'
        self.fields['kind'].label = 'Вид животного'
        self.fields['logo'].label = 'Логотип'

feedback/forms.py
# -*- coding: utf-8 -*-

__author__ = 'dimuska139'


from django.forms import ModelForm

from .models import Feedback


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        exclude = (
            'user',
            'status',
            'create_time',
        )

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = 'Сообщение'
        self.fields['name'].label = 'Ваше имя'

feedback/views.py
# coding: utf-8

from django.views.decorators.http import require_POST
from honeypot.decorators import check_honeypot
from jsonview.decorators import json_view

from feedback.forms import FeedbackForm
from utils.forms import get_errors


@json_view
@require_POST
@check_honeypot(field_name='hp')
def create(request):
    feedback_form = FeedbackForm(request.POST)
    errors = get_errors(feedback_form)
    if len(errors) > 0:
        response = {
            'success': False,
            'errors': errors
        }
        return response

    feedback_form.save()

    return {
        'success': True,
        'message': 'Ваше сообщение отправлено',
    }

templates/forms/feedback.html
{% load staticfiles honeypot %}
<div class="row">
    <div class="col-sm-6 form-group{% if form.name.errors %} has-danger{% endif %}">
        <input class="form-control w-100" id="id_name" name="{{ form.name.name }}" placeholder="{{ form.name.label }}" type="text" required value="{{ form.name.value }}">
        <div class="form-control-feedback">{{ form.name.errors }}</div>
    </div>
    <div class="col-sm-6 form-group{% if form.email.errors %} has-danger{% endif %}">
        <input class="form-control w-100" id="id_email" name="{{ form.email.name }}" placeholder="{{ form.email.label }}" type="email" required value="{{ form.email.value }}">
        <div class="form-control-feedback">{{ form.email.errors }}</div>
    </div>
    <div class="col-sm-12 form-group{% if form.text.errors %} has-danger{% endif %}">
        <textarea class="form-control" id="id_text" name="{{ form.text.name }}" placeholder="Сообщение" rows="5"></textarea>
        <div class="form-control-feedback">{{ form.text.errors }}</div>
    </div>
</div>
{% render_honeypot_field "hp" %}
<div class="alert alert-danger non-field-errors" role="alert">
    {{ form.non_field_errors }}
</div>
<div class="success alert alert-success" role="alert"></div>
<div class="row">
    <div class="col-sm-12 form-group text-right">
        <img class="loading-indicator" src="{% static 'img/loading.gif' %}">
        <button class="btn btn-success" type="submit">Отправить</button>
    </div>
</div>

templates/forms/login.html
{% load staticfiles %}
{% csrf_token %}
{% if next %}
    <input type="hidden" value="{{ next }}" name="next">
{% endif %}
<div class="card-block">
    <div class="row">
        <div class="col-sm-12">
            <h4 class="card-title">Авторизация</h4>
        </div>
    </div>
    <div class="form-group{% if form.username.errors %} has-danger{% endif %}">
        <label class="control-label">{{ form.username.label_tag }}</label>
        <input type="email" class="form-control" id="id_username" name="{{ form.username.name }}" placeholder="{{ form.username.label }}">
        <div class="form-control-feedback">{{ form.username.errors }}</div>
    </div>
    <div class="form-group{% if form.password.errors %} has-danger{% endif %}">
        <label class="control-label">{{ form.password.label_tag }}</label>
        <input type="password" class="form-control" id="id_password" name="{{ form.password.name }}" placeholder="{{ form.password.label }}">
        <div class="form-control-feedback">{{ form.password.errors }}</div>
    </div>
    <div class="form-group">
        <div class="help-block text-right"><a href="{% url 'users.password.restore' %}">Забыли пароль?</a></div>
    </div>
    <div class="alert alert-danger non-field-errors" role="alert">
        {{ form.non_field_errors }}
    </div>
</div>
<div class="card-footer text-right">
    <a href="{% url 'social:begin' 'vk-oauth2' %}?next={{ request.path }}" class="vk-auth-button btn btn-xs update-landing pull-left"><i class="fa fa-vk"></i></a>
    <img class="loading-indicator" src="{% static 'img/loading.gif' %}">
    <button type="submit" class="submit-button btn btn-success">Войти</button>
</div>

templates/forms/login_popup.html
{% csrf_token %}
<div class="form-group">
     <input type="email" name="username" class="form-control w-100{% if form.username.errors %} has-danger{% endif %}" id="exampleInputEmail2" placeholder="Email" required="">
    <div class="form-control-feedback">{{ form.username.errors }}</div>
</div>
<div class="form-group">
     <input type="password" name="password" class="form-control w-100{% if form.password.errors %} has-danger{% endif %}" id="exampleInputPassword2" placeholder="Пароль" required="">
    <div class="form-control-feedback">{{ form.password.errors }}</div>
     <div class="help-block text-right"><a href="">Забыли пароль?</a></div>
    <div class="help-block text-right"><a href="{% url 'sign_in' %}">Зарегистрироваться</a></div>
</div>
{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
{% endif %}
<div class="form-group">
     <button type="submit" class="btn btn-primary btn-block">Войти</button>
</div>

templates/forms/registration.html
{% load staticfiles %}
{% csrf_token %}
<div class="card-block">
    <div class="row">
        <div class="col-md-12">
            <h4 class="card-title">Регистрация</h4>
        </div>
    </div>
    <div class="form-group{% if form.email.errors %} has-danger{% endif %}">
        <label class="control-label">{{ form.email.label_tag }}</label>
        <input id="id_email" type="email" class="form-control" name="{{ form.email.name }}" placeholder="{{ form.email.label }}">
        <div class="form-control-feedback">{{ form.email.errors }}</div>
    </div>
    <div class="alert alert-danger non-field-errors" role="alert">
        {{ form.non_field_errors }}
    </div>
</div>
<div class="card-footer text-right">
    <img class="loading-indicator" src="{% static 'img/loading.gif' %}">
    <button type="submit" class="submit-button btn btn-success">Создать учётную запись</button>
</div>